### ISSUE TITLE
CEF vs Chromium

### ISSUE THREAD

**Issue by notspiff** [AlwinEsch/web.browser.chromium#1]
hi,

not so much an issue as a question. Say I don't want to use blink, since chromium ate my babies.  How tied is this to CEF and how tied is it to chrome ? Reason I ask is that servo should be CEF compatible, and i'd much rather use servo eventually..

**Comment by AlwinEsch** [comment]
CEF need always Chromium as source, only what make it problematic is that the from them created API need to make changes on Chromium itself to pass needed calls to the CEF library which make it impossible to use a normal Chromium or the Google Chrome direct for it.

The full functionality of Chromium is supported with CEF, only later are browser add-ons for there needed which then use Kodi instead of normal web parts e.g. Adobe Flash Player.

With the special parts of Google Chrome I'm not complete sure which can be in and not, seen only on forums that there is something possible.

My latest work on them was to reduce the binary library with only required parts (no cefclient and cefsimple anymore inside) see https://bitbucket.org/kodi-web/cef/downloads.

And has created the https://github.com/kodi-web/cef-binary-packages for binary lib updates without direct changes on add-on itself like the repo-plugins.

**Comment by notspiff** [comment]
https://github.com/servo/servo/tree/master/ports/cef to see what i was on about. as long as there is only cef calls, the preloading (or equivalent) should in theory work. but anyways, too early for you to bother with in any case.
